# Generated by Django 6.0.2 on 2026-03-18 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NGO',
                'verbose_name_plural': 'NGOs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_slots',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of employee slots', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='ngo',
            field=models.ForeignKey(blank=True, help_text='The NGO organising this activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ngo.ngo'),
        ),
    ]
