# Generated by Django 6.0.2 on 2026-03-31 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_ngo_alter_activity_max_slots_activity_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_slots',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='ngo.ngo'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
